services:
  - type: web
    name: nova-asia
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn eventlet
    startCommand: gunicorn --worker-class eventlet -w 1 wsgi:app
