services:
  - type: web
    name: nova-asia
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet --timeout 120 -w 1 wsgi:app
