services:
  - type: web
    name: nova-asia-test
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn
    startCommand: gunicorn wsgi:app
