services:
  - type: web
    name: nova-asia-test
    runtime: python
    buildCommand: pip install -r requirements.txt  # 强制使用 pip
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PIP_NO_CACHE_DIR
        value: "false"
